"""user_ip and techical data  tables created

Revision ID: 0fe52fa81506
Revises: 2add88ca89e2
Create Date: 2025-11-16 12:59:02.270947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe52fa81506'
down_revision: Union[str, Sequence[str], None] = '2add88ca89e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('techical_data',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('insert_id', sa.String(), nullable=True),
    sa.Column('amplitude_attribution_ids', sa.JSON(), nullable=True),
    sa.Column('amplitude_id', sa.BigInteger(), nullable=True),
    sa.Column('is_attribution_event', sa.String(), nullable=True),
    sa.Column('library', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('user_ip',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.alter_column('mp', 'insert_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
# Populate the new table with unique data from 'mp' 
    op.execute(""" 
               INSERT INTO techical_data (uuid, insert_id, amplitude_attribution_ids, amplitude_id, is_attribution_event, library) 
               SELECT uuid, insert_id, amplitude_attribution_ids, amplitude_id, is_attribution_event, library 
               FROM mp 
               ON CONFLICT (uuid) DO NOTHING
               """) 
    # Populate the new table with unique data from 'mp' 
    op.execute(""" 
               INSERT INTO user_ip (uuid, ip_address) 
               SELECT uuid, ip_address 
               FROM mp 
               ON CONFLICT (uuid) DO NOTHING 
               """)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('mp', 'insert_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('user_ip')
    op.drop_table('techical_data')
    # ### end Alembic commands ###
