"""change primary_key to uuid

Revision ID: 2add88ca89e2
Revises: d5386309b5cb
Create Date: 2025-11-15 20:55:14.821177

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2add88ca89e2"
down_revision: Union[str, Sequence[str], None] = "d5386309b5cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("mp", "uuid", existing_type=sa.VARCHAR(), nullable=False)
    op.create_primary_key("mp_pkey", "mp", ["uuid"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("mp_pkey", "mp", type_="primary")
    op.alter_column("mp", "uuid", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
