"""Remove indexes from MpEvent

Revision ID: 3e41873dea3d
Revises: da342dc39914
Create Date: 2025-11-12 12:07:57.686420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e41873dea3d'
down_revision: Union[str, Sequence[str], None] = 'da342dc39914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mp_client_event_time'), table_name='mp')
    op.drop_index(op.f('ix_mp_insert_id'), table_name='mp')
    op.drop_index(op.f('ix_web_client_event_time'), table_name='web')
    op.drop_index(op.f('ix_web_insert_id'), table_name='web')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_web_insert_id'), 'web', ['insert_id'], unique=False)
    op.create_index(op.f('ix_web_client_event_time'), 'web', ['client_event_time'], unique=False)
    op.create_index(op.f('ix_mp_insert_id'), 'mp', ['insert_id'], unique=False)
    op.create_index(op.f('ix_mp_client_event_time'), 'mp', ['client_event_time'], unique=False)
    # ### end Alembic commands ###
