"""user_locations table created

Revision ID: 43647dddc40c
Revises: 5fbc1cfb5c4c
Create Date: 2025-11-15 19:53:13.645942

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "43647dddc40c"
down_revision: Union[str, Sequence[str], None] = "5fbc1cfb5c4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_locations",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("location_lat", sa.Float(), nullable=True),
        sa.Column("location_lng", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###

    # Populate the new table with unique data from 'mp'
    op.execute("""
        INSERT INTO user_locations (uuid, location_lat, location_lng)
        SELECT uuid, location_lat, location_lng
        FROM mp
        ON CONFLICT (uuid) DO NOTHING
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_locations")
    # ### end Alembic commands ###
