"""mobile devise data deleted from mp

Revision ID: 5fbc1cfb5c4c
Revises: a8c6dcc8c3ae
Create Date: 2025-11-15 19:37:39.018802

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5fbc1cfb5c4c"
down_revision: Union[str, Sequence[str], None] = "a8c6dcc8c3ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "mp", "mobile_devices", ["device_id"], ["device_id"])
    op.drop_column("mp", "device_model")
    op.drop_column("mp", "device_type")
    op.drop_column("mp", "device_brand")
    op.drop_column("mp", "device_manufacturer")
    op.drop_column("mp", "device_family")
    op.drop_column("mp", "device_carrier")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mp",
        sa.Column("device_carrier", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "mp",
        sa.Column("device_family", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "mp",
        sa.Column(
            "device_manufacturer", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "mp",
        sa.Column("device_brand", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "mp", sa.Column("device_type", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "mp",
        sa.Column("device_model", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "mp", type_="foreignkey")
    # ### end Alembic commands ###

    # Restore data back to 'mp' from 'mobile_devices'
    op.execute("""
        UPDATE mp
        SET 
            device_brand = md.device_brand,
            device_carrier = md.device_carrier,
            device_family = md.device_family,
            device_manufacturer = md.device_manufacturer,
            device_model = md.device_model,
            device_type = md.device_type
        FROM mobile_devices md
        WHERE mp.device_id = md.device_id
    """)
