"""mobile_devices table created and populated from mp

Revision ID: a8c6dcc8c3ae
Revises: ad247ff99d82
Create Date: 2025-11-15 18:51:37.309196

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a8c6dcc8c3ae"
down_revision: Union[str, Sequence[str], None] = "ad247ff99d82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mobile_devices",
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("device_brand", sa.String(), nullable=True),
        sa.Column("device_carrier", sa.String(), nullable=True),
        sa.Column("device_family", sa.String(), nullable=True),
        sa.Column("device_manufacturer", sa.String(), nullable=True),
        sa.Column("device_model", sa.String(), nullable=True),
        sa.Column("device_type", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("device_id"),
    )
    # ### end Alembic commands ###

    # Populate the new table with unique data from 'mp'
    op.execute("""
        INSERT INTO mobile_devices (device_id, device_brand, device_carrier, device_family, device_manufacturer, device_model, device_type)
        SELECT DISTINCT device_id, device_brand, device_carrier, device_family, device_manufacturer, device_model, device_type
        FROM mp
        WHERE device_id IS NOT NULL
        ON CONFLICT (device_id) DO NOTHING
    """)


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mobile_devices")
    # ### end Alembic commands ###
