"""Deleted empty columns

Revision ID: ad247ff99d82
Revises: 3e41873dea3d
Create Date: 2025-11-15 18:36:18.407928

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ad247ff99d82"
down_revision: Union[str, Sequence[str], None] = "3e41873dea3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mp", "insert_key")
    op.drop_column("mp", "idfa")
    op.drop_column("mp", "server_received_time")
    op.drop_column("mp", "sample_rate")
    op.drop_column("mp", "processed_time")
    op.drop_column("mp", "schema")
    op.drop_column("mp", "source_id")
    op.drop_column("mp", "adid")
    op.drop_column("mp", "partner_id")
    op.drop_column("mp", "client_event_time")
    op.drop_column("mp", "dma")
    op.drop_column("mp", "extra_json")
    op.drop_column("mp", "server_upload_time")
    op.drop_column("mp", "user_creation_time")
    op.drop_column("mp", "client_upload_time")
    op.drop_column("mp", "amplitude_event_type")
    op.drop_column("mp", "paying")
    op.drop_column("mp", "global_user_properties")
    op.drop_column("mp", "app")
    op.drop_column("mp", "data_type")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mp",
        sa.Column(
            "global_user_properties", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "mp", sa.Column("paying", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "mp",
        sa.Column(
            "amplitude_event_type", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "mp",
        sa.Column(
            "client_upload_time",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "mp",
        sa.Column(
            "user_creation_time",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "mp",
        sa.Column(
            "server_upload_time",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "mp",
        sa.Column(
            "extra_json",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "mp", sa.Column("dma", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "mp",
        sa.Column(
            "client_event_time",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "mp", sa.Column("partner_id", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "mp", sa.Column("adid", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "mp", sa.Column("source_id", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "mp", sa.Column("schema", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "mp",
        sa.Column(
            "processed_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "mp",
        sa.Column(
            "sample_rate",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "mp",
        sa.Column(
            "server_received_time",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "mp", sa.Column("idfa", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "mp", sa.Column("insert_key", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "mp", sa.Column("app", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "mp", sa.Column("data_type", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
