"""user ip and techical  data deleted from mp

Revision ID: c3e87f7b4a02
Revises: 0fe52fa81506
Create Date: 2025-11-16 13:26:23.955973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3e87f7b4a02'
down_revision: Union[str, Sequence[str], None] = '0fe52fa81506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('mp_uuid_fkey'), 'mp', type_='foreignkey')
    op.drop_column('mp', 'insert_id')
    op.drop_column('mp', 'is_attribution_event')
    op.drop_column('mp', 'amplitude_attribution_ids')
    op.drop_column('mp', 'ip_address')
    op.drop_column('mp', 'amplitude_id')
    op.drop_column('mp', 'library')
    op.create_foreign_key(None, 'techical_data', 'mp', ['uuid'], ['uuid'])
    op.create_foreign_key(None, 'user_ip', 'mp', ['uuid'], ['uuid'])
    op.create_foreign_key(None, 'user_locations', 'mp', ['uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_locations', type_='foreignkey')
    op.drop_constraint(None, 'user_ip', type_='foreignkey')
    op.drop_constraint(None, 'techical_data', type_='foreignkey')
    op.add_column('mp', sa.Column('library', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mp', sa.Column('amplitude_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('mp', sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mp', sa.Column('amplitude_attribution_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('mp', sa.Column('is_attribution_event', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mp', sa.Column('insert_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('mp_uuid_fkey'), 'mp', 'user_locations', ['uuid'], ['uuid'])
    # ### end Alembic commands ###


    # Restore data back to 'mp' from 'mobile_devices'
    op.execute("""
        UPDATE mp
        SET 
            location_lng = ul.location_lng,
            location_lat = ul.location_lat,
        FROM user_locations ul
        WHERE mp.uuid = ul.uuid
    """)
    op.execute("""
        UPDATE mp
        SET 
            ip_address = uip.ip_address
        FROM user_ip uip
        WHERE mp.uuid = uip.uuid
    """)