"""user locations data deleted from mp

Revision ID: d5386309b5cb
Revises: 43647dddc40c
Create Date: 2025-11-15 20:44:46.722759

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d5386309b5cb"
down_revision: Union[str, Sequence[str], None] = "43647dddc40c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "mp", "user_locations", ["uuid"], ["uuid"])
    op.drop_column("mp", "location_lat")
    op.drop_column("mp", "location_lng")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mp",
        sa.Column(
            "location_lng",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "mp",
        sa.Column(
            "location_lat",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "mp", type_="foreignkey")
    # ### end Alembic commands ###

    # Restore data back to 'mp' from 'mobile_devices'
    op.execute("""
        UPDATE mp
        SET 
            location_lng = ul.location_lng,
            location_lat = ul.location_lat,
        FROM user_locations ul
        WHERE mp.uuid = ul.uuid
    """)
