"""new columns

Revision ID: da342dc39914
Revises: cf5a9692af51
Create Date: 2025-11-07 15:19:35.420988

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "da342dc39914"
down_revision: Union[str, Sequence[str], None] = "cf5a9692af51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mp", sa.Column("insert_id", sa.String(), nullable=False))
    op.add_column("mp", sa.Column("insert_key", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("schema", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("adid", sa.String(), nullable=True))
    op.add_column(
        "mp", sa.Column("amplitude_attribution_ids", sa.JSON(), nullable=True)
    )
    op.add_column("mp", sa.Column("amplitude_event_type", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("amplitude_id", sa.BigInteger(), nullable=True))
    op.add_column("mp", sa.Column("app", sa.Integer(), nullable=True))
    op.add_column("mp", sa.Column("city", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("client_event_time", sa.DateTime(), nullable=False))
    op.add_column("mp", sa.Column("client_upload_time", sa.DateTime(), nullable=True))
    op.add_column("mp", sa.Column("country", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("data_type", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("device_brand", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("device_carrier", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("device_family", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("device_id", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("device_manufacturer", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("device_model", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("device_type", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("dma", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("event_id", sa.Integer(), nullable=True))
    op.add_column("mp", sa.Column("event_time", sa.DateTime(), nullable=True))
    op.add_column("mp", sa.Column("event_type", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("global_user_properties", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("idfa", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("ip_address", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("is_attribution_event", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("language", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("library", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("location_lat", sa.Float(), nullable=True))
    op.add_column("mp", sa.Column("location_lng", sa.Float(), nullable=True))
    op.add_column("mp", sa.Column("os_name", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("os_version", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("partner_id", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("paying", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("platform", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("processed_time", sa.DateTime(), nullable=True))
    op.add_column("mp", sa.Column("region", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("sample_rate", sa.Float(), nullable=True))
    op.add_column("mp", sa.Column("server_received_time", sa.DateTime(), nullable=True))
    op.add_column("mp", sa.Column("server_upload_time", sa.DateTime(), nullable=True))
    op.add_column("mp", sa.Column("session_id", sa.BigInteger(), nullable=True))
    op.add_column("mp", sa.Column("source_id", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("start_version", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("user_creation_time", sa.DateTime(), nullable=True))
    op.add_column("mp", sa.Column("user_id", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("uuid", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("version_name", sa.String(), nullable=True))
    op.add_column("mp", sa.Column("data_json", sa.JSON(), nullable=True))
    op.add_column("mp", sa.Column("event_properties_json", sa.JSON(), nullable=True))
    op.add_column("mp", sa.Column("group_properties_json", sa.JSON(), nullable=True))
    op.add_column("mp", sa.Column("groups_json", sa.JSON(), nullable=True))
    op.add_column("mp", sa.Column("plan_json", sa.JSON(), nullable=True))
    op.add_column("mp", sa.Column("user_properties_json", sa.JSON(), nullable=True))
    op.add_column("mp", sa.Column("extra_json", sa.JSON(), nullable=True))
    op.drop_index(op.f("ix_mp_created_at"), table_name="mp")
    op.drop_index(op.f("ix_mp_id"), table_name="mp")
    op.create_index(
        op.f("ix_mp_client_event_time"), "mp", ["client_event_time"], unique=False
    )
    op.create_index(op.f("ix_mp_insert_id"), "mp", ["insert_id"], unique=False)
    op.drop_column("mp", "data")
    op.drop_column("mp", "id")
    op.drop_column("mp", "created_at")
    op.add_column("web", sa.Column("insert_id", sa.String(), nullable=False))
    op.add_column("web", sa.Column("insert_key", sa.String(), nullable=True))
    op.add_column("web", sa.Column("schema", sa.String(), nullable=True))
    op.add_column("web", sa.Column("adid", sa.String(), nullable=True))
    op.add_column(
        "web", sa.Column("amplitude_attribution_ids", sa.JSON(), nullable=True)
    )
    op.add_column("web", sa.Column("amplitude_event_type", sa.String(), nullable=True))
    op.add_column("web", sa.Column("amplitude_id", sa.BigInteger(), nullable=True))
    op.add_column("web", sa.Column("app", sa.Integer(), nullable=True))
    op.add_column("web", sa.Column("city", sa.String(), nullable=True))
    op.add_column("web", sa.Column("client_event_time", sa.DateTime(), nullable=False))
    op.add_column("web", sa.Column("client_upload_time", sa.DateTime(), nullable=True))
    op.add_column("web", sa.Column("country", sa.String(), nullable=True))
    op.add_column("web", sa.Column("data_type", sa.String(), nullable=True))
    op.add_column("web", sa.Column("device_brand", sa.String(), nullable=True))
    op.add_column("web", sa.Column("device_carrier", sa.String(), nullable=True))
    op.add_column("web", sa.Column("device_family", sa.String(), nullable=True))
    op.add_column("web", sa.Column("device_id", sa.String(), nullable=True))
    op.add_column("web", sa.Column("device_manufacturer", sa.String(), nullable=True))
    op.add_column("web", sa.Column("device_model", sa.String(), nullable=True))
    op.add_column("web", sa.Column("device_type", sa.String(), nullable=True))
    op.add_column("web", sa.Column("dma", sa.String(), nullable=True))
    op.add_column("web", sa.Column("event_id", sa.Integer(), nullable=True))
    op.add_column("web", sa.Column("event_time", sa.DateTime(), nullable=True))
    op.add_column("web", sa.Column("event_type", sa.String(), nullable=True))
    op.add_column(
        "web", sa.Column("global_user_properties", sa.String(), nullable=True)
    )
    op.add_column("web", sa.Column("idfa", sa.String(), nullable=True))
    op.add_column("web", sa.Column("ip_address", sa.String(), nullable=True))
    op.add_column("web", sa.Column("is_attribution_event", sa.String(), nullable=True))
    op.add_column("web", sa.Column("language", sa.String(), nullable=True))
    op.add_column("web", sa.Column("library", sa.String(), nullable=True))
    op.add_column("web", sa.Column("location_lat", sa.Float(), nullable=True))
    op.add_column("web", sa.Column("location_lng", sa.Float(), nullable=True))
    op.add_column("web", sa.Column("os_name", sa.String(), nullable=True))
    op.add_column("web", sa.Column("os_version", sa.String(), nullable=True))
    op.add_column("web", sa.Column("partner_id", sa.String(), nullable=True))
    op.add_column("web", sa.Column("paying", sa.String(), nullable=True))
    op.add_column("web", sa.Column("platform", sa.String(), nullable=True))
    op.add_column("web", sa.Column("processed_time", sa.DateTime(), nullable=True))
    op.add_column("web", sa.Column("region", sa.String(), nullable=True))
    op.add_column("web", sa.Column("sample_rate", sa.Float(), nullable=True))
    op.add_column(
        "web", sa.Column("server_received_time", sa.DateTime(), nullable=True)
    )
    op.add_column("web", sa.Column("server_upload_time", sa.DateTime(), nullable=True))
    op.add_column("web", sa.Column("session_id", sa.BigInteger(), nullable=True))
    op.add_column("web", sa.Column("source_id", sa.String(), nullable=True))
    op.add_column("web", sa.Column("start_version", sa.String(), nullable=True))
    op.add_column("web", sa.Column("user_creation_time", sa.DateTime(), nullable=True))
    op.add_column("web", sa.Column("user_id", sa.String(), nullable=True))
    op.add_column("web", sa.Column("uuid", sa.String(), nullable=True))
    op.add_column("web", sa.Column("version_name", sa.String(), nullable=True))
    op.add_column("web", sa.Column("data_json", sa.JSON(), nullable=True))
    op.add_column("web", sa.Column("event_properties_json", sa.JSON(), nullable=True))
    op.add_column("web", sa.Column("group_properties_json", sa.JSON(), nullable=True))
    op.add_column("web", sa.Column("groups_json", sa.JSON(), nullable=True))
    op.add_column("web", sa.Column("plan_json", sa.JSON(), nullable=True))
    op.add_column("web", sa.Column("user_properties_json", sa.JSON(), nullable=True))
    op.add_column("web", sa.Column("extra_json", sa.JSON(), nullable=True))
    op.drop_index(op.f("ix_web_created_at"), table_name="web")
    op.drop_index(op.f("ix_web_id"), table_name="web")
    op.create_index(
        op.f("ix_web_client_event_time"), "web", ["client_event_time"], unique=False
    )
    op.create_index(op.f("ix_web_insert_id"), "web", ["insert_id"], unique=False)
    op.drop_column("web", "data")
    op.drop_column("web", "id")
    op.drop_column("web", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "web",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "web",
        sa.Column(
            "id",
            sa.VARCHAR(),
            server_default=sa.text("nextval('web_id_seq'::regclass)"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "web",
        sa.Column(
            "data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_web_insert_id"), table_name="web")
    op.drop_index(op.f("ix_web_client_event_time"), table_name="web")
    op.create_index(op.f("ix_web_id"), "web", ["id"], unique=False)
    op.create_index(op.f("ix_web_created_at"), "web", ["created_at"], unique=False)
    op.drop_column("web", "extra_json")
    op.drop_column("web", "user_properties_json")
    op.drop_column("web", "plan_json")
    op.drop_column("web", "groups_json")
    op.drop_column("web", "group_properties_json")
    op.drop_column("web", "event_properties_json")
    op.drop_column("web", "data_json")
    op.drop_column("web", "version_name")
    op.drop_column("web", "uuid")
    op.drop_column("web", "user_id")
    op.drop_column("web", "user_creation_time")
    op.drop_column("web", "start_version")
    op.drop_column("web", "source_id")
    op.drop_column("web", "session_id")
    op.drop_column("web", "server_upload_time")
    op.drop_column("web", "server_received_time")
    op.drop_column("web", "sample_rate")
    op.drop_column("web", "region")
    op.drop_column("web", "processed_time")
    op.drop_column("web", "platform")
    op.drop_column("web", "paying")
    op.drop_column("web", "partner_id")
    op.drop_column("web", "os_version")
    op.drop_column("web", "os_name")
    op.drop_column("web", "location_lng")
    op.drop_column("web", "location_lat")
    op.drop_column("web", "library")
    op.drop_column("web", "language")
    op.drop_column("web", "is_attribution_event")
    op.drop_column("web", "ip_address")
    op.drop_column("web", "idfa")
    op.drop_column("web", "global_user_properties")
    op.drop_column("web", "event_type")
    op.drop_column("web", "event_time")
    op.drop_column("web", "event_id")
    op.drop_column("web", "dma")
    op.drop_column("web", "device_type")
    op.drop_column("web", "device_model")
    op.drop_column("web", "device_manufacturer")
    op.drop_column("web", "device_id")
    op.drop_column("web", "device_family")
    op.drop_column("web", "device_carrier")
    op.drop_column("web", "device_brand")
    op.drop_column("web", "data_type")
    op.drop_column("web", "country")
    op.drop_column("web", "client_upload_time")
    op.drop_column("web", "client_event_time")
    op.drop_column("web", "city")
    op.drop_column("web", "app")
    op.drop_column("web", "amplitude_id")
    op.drop_column("web", "amplitude_event_type")
    op.drop_column("web", "amplitude_attribution_ids")
    op.drop_column("web", "adid")
    op.drop_column("web", "schema")
    op.drop_column("web", "insert_key")
    op.drop_column("web", "insert_id")
    op.add_column(
        "mp",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "mp",
        sa.Column(
            "id",
            sa.VARCHAR(),
            server_default=sa.text("nextval('mp_id_seq'::regclass)"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "mp",
        sa.Column(
            "data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_mp_insert_id"), table_name="mp")
    op.drop_index(op.f("ix_mp_client_event_time"), table_name="mp")
    op.create_index(op.f("ix_mp_id"), "mp", ["id"], unique=False)
    op.create_index(op.f("ix_mp_created_at"), "mp", ["created_at"], unique=False)
    op.drop_column("mp", "extra_json")
    op.drop_column("mp", "user_properties_json")
    op.drop_column("mp", "plan_json")
    op.drop_column("mp", "groups_json")
    op.drop_column("mp", "group_properties_json")
    op.drop_column("mp", "event_properties_json")
    op.drop_column("mp", "data_json")
    op.drop_column("mp", "version_name")
    op.drop_column("mp", "uuid")
    op.drop_column("mp", "user_id")
    op.drop_column("mp", "user_creation_time")
    op.drop_column("mp", "start_version")
    op.drop_column("mp", "source_id")
    op.drop_column("mp", "session_id")
    op.drop_column("mp", "server_upload_time")
    op.drop_column("mp", "server_received_time")
    op.drop_column("mp", "sample_rate")
    op.drop_column("mp", "region")
    op.drop_column("mp", "processed_time")
    op.drop_column("mp", "platform")
    op.drop_column("mp", "paying")
    op.drop_column("mp", "partner_id")
    op.drop_column("mp", "os_version")
    op.drop_column("mp", "os_name")
    op.drop_column("mp", "location_lng")
    op.drop_column("mp", "location_lat")
    op.drop_column("mp", "library")
    op.drop_column("mp", "language")
    op.drop_column("mp", "is_attribution_event")
    op.drop_column("mp", "ip_address")
    op.drop_column("mp", "idfa")
    op.drop_column("mp", "global_user_properties")
    op.drop_column("mp", "event_type")
    op.drop_column("mp", "event_time")
    op.drop_column("mp", "event_id")
    op.drop_column("mp", "dma")
    op.drop_column("mp", "device_type")
    op.drop_column("mp", "device_model")
    op.drop_column("mp", "device_manufacturer")
    op.drop_column("mp", "device_id")
    op.drop_column("mp", "device_family")
    op.drop_column("mp", "device_carrier")
    op.drop_column("mp", "device_brand")
    op.drop_column("mp", "data_type")
    op.drop_column("mp", "country")
    op.drop_column("mp", "client_upload_time")
    op.drop_column("mp", "client_event_time")
    op.drop_column("mp", "city")
    op.drop_column("mp", "app")
    op.drop_column("mp", "amplitude_id")
    op.drop_column("mp", "amplitude_event_type")
    op.drop_column("mp", "amplitude_attribution_ids")
    op.drop_column("mp", "adid")
    op.drop_column("mp", "schema")
    op.drop_column("mp", "insert_key")
    op.drop_column("mp", "insert_id")
    op.create_table(
        "test",
        sa.Column("user_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "username", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("email", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "registration_date",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("users_pkey")),
        sa.UniqueConstraint(
            "email",
            name=op.f("users_email_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "username",
            name=op.f("users_username_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
