from sqlalchemy import Column, String, Integer, Float, DateTime, JSON, BigInteger
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class WebEvent(Base):
    __tablename__ = "web"
    insert_id = Column(String, primary_key=True, index=True)
    insert_key = Column(String)
    schema = Column(String)
    adid = Column(String)
    amplitude_attribution_ids = Column(JSON)
    amplitude_event_type = Column(String)
    amplitude_id = Column(BigInteger)
    app = Column(Integer)
    city = Column(String)
    client_event_time = Column(DateTime, nullable=False, index=True)
    client_upload_time = Column(DateTime)
    country = Column(String)
    data_type = Column(String)
    device_brand = Column(String)
    device_carrier = Column(String)
    device_family = Column(String)
    device_id = Column(String)
    device_manufacturer = Column(String)
    device_model = Column(String)
    device_type = Column(String)
    dma = Column(String)
    event_id = Column(Integer)
    event_time = Column(DateTime)
    event_type = Column(String)
    global_user_properties = Column(String)
    idfa = Column(String)
    ip_address = Column(String)
    is_attribution_event = Column(String)
    language = Column(String)
    library = Column(String)
    location_lat = Column(Float)
    location_lng = Column(Float)
    os_name = Column(String)
    os_version = Column(String)
    partner_id = Column(String)
    paying = Column(String)
    platform = Column(String)
    processed_time = Column(DateTime)
    region = Column(String)
    sample_rate = Column(Float)
    server_received_time = Column(DateTime)
    server_upload_time = Column(DateTime)
    session_id = Column(BigInteger)
    source_id = Column(String)
    start_version = Column(String)
    user_creation_time = Column(DateTime)
    user_id = Column(String)
    uuid = Column(String)
    version_name = Column(String)
    data_json = Column(JSON)
    event_properties_json = Column(JSON)
    group_properties_json = Column(JSON)
    groups_json = Column(JSON)
    plan_json = Column(JSON)
    user_properties_json = Column(JSON)
    extra_json = Column(JSON)


class MpEvent(Base):
    __tablename__ = "mp"
    insert_id = Column(String, primary_key=True, index=True)
    insert_key = Column(String)
    schema = Column(String)
    adid = Column(String)
    amplitude_attribution_ids = Column(JSON)
    amplitude_event_type = Column(String)
    amplitude_id = Column(BigInteger)
    app = Column(Integer)
    city = Column(String)
    client_event_time = Column(DateTime, nullable=False, index=True)
    client_upload_time = Column(DateTime)
    country = Column(String)
    data_type = Column(String)
    device_brand = Column(String)
    device_carrier = Column(String)
    device_family = Column(String)
    device_id = Column(String)
    device_manufacturer = Column(String)
    device_model = Column(String)
    device_type = Column(String)
    dma = Column(String)
    event_id = Column(Integer)
    event_time = Column(DateTime)
    event_type = Column(String)
    global_user_properties = Column(String)
    idfa = Column(String)
    ip_address = Column(String)
    is_attribution_event = Column(String)
    language = Column(String)
    library = Column(String)
    location_lat = Column(Float)
    location_lng = Column(Float)
    os_name = Column(String)
    os_version = Column(String)
    partner_id = Column(String)
    paying = Column(String)
    platform = Column(String)
    processed_time = Column(DateTime)
    region = Column(String)
    sample_rate = Column(Float)
    server_received_time = Column(DateTime)
    server_upload_time = Column(DateTime)
    session_id = Column(BigInteger)
    source_id = Column(String)
    start_version = Column(String)
    user_creation_time = Column(DateTime)
    user_id = Column(String)
    uuid = Column(String)
    version_name = Column(String)
    data_json = Column(JSON)
    event_properties_json = Column(JSON)
    group_properties_json = Column(JSON)
    groups_json = Column(JSON)
    plan_json = Column(JSON)
    user_properties_json = Column(JSON)
    extra_json = Column(JSON)
